=== dusanlazic/xml-ws-2022/backends/autorska/data/a1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.0" vc:maxVersion="1.1" targetNamespace="http://www.zavod.com/Autorska"
           xmlns:a="http://www.zavod.com/Autorska">

    <xs:element name="Zahtevi">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="Zahtev" type="a:TZahtev"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TZahtev">
        <xs:sequence>
            <xs:element name="Podnosilac" type="a:TLice"/>
            <xs:element name="Delo" type="a:TDelo"/>
            <xs:element minOccurs="0" name="Autor">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="a:TFizicko_Lice">
                            <xs:sequence>
                                <xs:element minOccurs="0" name="godina_smrti" type="xs:date"/>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="Informacije_Zavoda" type="a:TInformacije_Zavoda"/>
            <xs:element minOccurs="0" name="Punomocnik" type="a:TFizicko_Lice"/>
            <xs:element name="Informacije_Sistema" type="a:TInformacije_Sistema"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element minOccurs="0" name="telefon" type="xs:string"/>
            <xs:element minOccurs="0" name="email" type="xs:string"/>
            <xs:element minOccurs="0" name="pseudonim" nillable="true" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_Lice">
        <xs:complexContent>
            <xs:extension base="a:TLice">
                <xs:sequence>
                    <xs:element name="prezime" type="xs:string"/>
                    <xs:element name="adresa" type="xs:string"/>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravno_Lice">
        <xs:complexContent>
            <xs:extension base="a:TLice">
                <xs:sequence>
                    <xs:element name="sediste" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TDelo">
        <xs:sequence>
            <xs:element name="naslov" type="xs:string"/>
            <xs:element name="alternativni_naslov" type="xs:string"/>
            <xs:element name="vrsta_dela" type="xs:string"/>
            <xs:element name="forma_zapisa" type="xs:string"/>
            <xs:element name="radni_odnos" type="xs:boolean"/>
            <xs:element name="nacin_koriscenja" type="xs:string"/>
            <xs:element minOccurs="0" name="Prerada">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="originalni_naslov" type="xs:string"/>
                        <xs:element name="Originalni_Autor">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="ime" type="xs:string"/>
                                    <xs:element name="prezime" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TInformacije_Zavoda">
        <xs:sequence>
            <xs:element ref="a:broj_prijave"/>
            <xs:element name="datum_podnosenja" type="xs:date"/>
            <xs:element name="prilozi">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="primer_dela" type="a:TPrilog"/>
                        <xs:element name="opis_dela" type="a:TPrilog"/>
                        <xs:element name="punomocje" type="a:TPrilog"/>
                        <xs:element name="uplata" type="a:TPrilog"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TInformacije_Sistema">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="broj_prijave">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="A-[0-9]{4}-[0-9]{2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:complexType name="TPrilog">
        <xs:sequence>
            <xs:element name="putanja" type="xs:string"/>
            <xs:element name="naziv_datoteke" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dusanlazic/xml-ws-2022/backends/autorska/src/main/resources/xml/zahtevi/A-0000-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:Zahtev xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:a="http://www.zavod.com/Autorska"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.zavod.com/Autorska file:/home/pavle/Documents/XML/Projekat/xml-ws-2022/backends/autorska/src/main/resources/xml/a1.xsd">
    <a:Podnosilac xsi:type="a:TPravno_Lice">
        <a:ime>ime1</a:ime>
        <a:sediste>sediste2</a:sediste>
    </a:Podnosilac>
    <a:Delo>
        <a:naslov>naslov0</a:naslov>
        <a:alternativni_naslov>alternativni_naslov0</a:alternativni_naslov>
        <a:vrsta_dela>vrsta_dela0</a:vrsta_dela>
        <a:forma_zapisa>forma_zapisa0</a:forma_zapisa>
        <a:radni_odnos>false</a:radni_odnos>
        <a:nacin_koriscenja>nacin_koriscenja0</a:nacin_koriscenja>
    </a:Delo>
    <a:Informacije_Zavoda>
        <a:broj_prijave>A-0000-01</a:broj_prijave>
        <a:datum_podnosenja>2006-05-04</a:datum_podnosenja>
        <a:prilozi>
            <a:primer_dela>
                <a:putanja>putanja0</a:putanja>
                <a:naziv_datoteke>naziv_datoteke0</a:naziv_datoteke>
            </a:primer_dela>
            <a:opis_dela>
                <a:putanja>putanja1</a:putanja>
                <a:naziv_datoteke>naziv_datoteke1</a:naziv_datoteke>
            </a:opis_dela>
            <a:punomocje>
                <a:putanja>putanja2</a:putanja>
                <a:naziv_datoteke>naziv_datoteke2</a:naziv_datoteke>
            </a:punomocje>
            <a:uplata>
                <a:putanja>putanja3</a:putanja>
                <a:naziv_datoteke>naziv_datoteke3</a:naziv_datoteke>
            </a:uplata>
        </a:prilozi>
    </a:Informacije_Zavoda>
    <a:Informacije_Sistema>
        <a:email>email0</a:email>
    </a:Informacije_Sistema>
</a:Zahtev>

=== dusanlazic/xml-ws-2022/backends/autorska/src/main/resources/xml/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:Zahtevi xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xmlns:a="http://www.zavod.com/Autorska"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.zavod.com/Autorska file:/home/pavle/Documents/XML/Projekat/xml-ws-2022/backends/autorska/src/main/resources/xml/a1.xsd">
    <a:Zahtev>
        <a:Podnosilac xsi:type="a:TPravno_Lice">
            <a:ime>Firma DOO</a:ime>
            <a:sediste>Dr Ivana Ribara 13</a:sediste>
        </a:Podnosilac>
        <a:Delo>
            <a:naslov>naslov0</a:naslov>
            <a:alternativni_naslov>alternativni_naslov0</a:alternativni_naslov>
            <a:vrsta_dela>vrsta_dela0</a:vrsta_dela>
            <a:forma_zapisa>forma_zapisa0</a:forma_zapisa>
            <a:radni_odnos>false</a:radni_odnos>
            <a:nacin_koriscenja>nacin_koriscenja0</a:nacin_koriscenja>
        </a:Delo>
        <a:Informacije_Zavoda>
            <a:opis_dela>opis_dela0</a:opis_dela>
            <a:primer_dela>
            </a:primer_dela>
            <a:broj_prijave>A-0</a:broj_prijave>
            <a:datum_podsnosenja>2006-05-04</a:datum_podsnosenja>
        </a:Informacije_Zavoda>
    </a:Zahtev>
    <a:Zahtev>
        <a:Podnosilac xsi:type="a:TFizicko_Lice">
            <a:ime>Petar</a:ime>
            <a:telefon>+38123456789</a:telefon>
            <a:email>pera@gmail.com</a:email>
            <a:prezime>Peric</a:prezime>
            <a:adresa>Maksima Gorkog 10</a:adresa>
            <a:drzavljanstvo>srpsko</a:drzavljanstvo>
        </a:Podnosilac>
        <a:Delo>
            <a:naslov>Izabrana dela</a:naslov>
            <a:alternativni_naslov>Perina izabrana dela</a:alternativni_naslov>
            <a:vrsta_dela>zbirka</a:vrsta_dela>
            <a:forma_zapisa>rukopis</a:forma_zapisa>
            <a:radni_odnos>false</a:radni_odnos>
            <a:nacin_koriscenja>nacin koriscenja</a:nacin_koriscenja>
        </a:Delo>
        <a:Informacije_Zavoda>
            <a:opis_dela>opis_dela1</a:opis_dela>
            <a:primer_dela>primer_dela1</a:primer_dela>
            <a:broj_prijave>A-1</a:broj_prijave>
            <a:datum_podsnosenja>2006-05-04</a:datum_podsnosenja>
        </a:Informacije_Zavoda>
    </a:Zahtev>
</a:Zahtevi>

=== dusanlazic/xml-ws-2022/backends/autorska/src/main/resources/xml/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:Zahtevi xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:a="http://www.zavod.com/Autorska"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.zavod.com/Autorska file:/home/pavle/Documents/XML/Projekat/xml-ws-2022/backends/autorska/src/main/resources/xml/a1.xsd">
    <a:Zahtev>
        <a:Podnosilac xsi:type="a:TPravno_Lice">
            <a:ime>Firma DOO</a:ime>
            <a:sediste>Dr Ivana Ribara 13</a:sediste>
        </a:Podnosilac>
        <a:Delo>
            <a:naslov>naslov0</a:naslov>
            <a:alternativni_naslov>alternativni_naslov0</a:alternativni_naslov>
            <a:vrsta_dela>vrsta_dela0</a:vrsta_dela>
            <a:forma_zapisa>forma_zapisa0</a:forma_zapisa>
            <a:radni_odnos>false</a:radni_odnos>
            <a:nacin_koriscenja>nacin_koriscenja0</a:nacin_koriscenja>
        </a:Delo>
        <a:Informacije_Zavoda>
            <a:broj_prijave>A-0000-00</a:broj_prijave>
            <a:datum_podsnosenja>2006-05-04</a:datum_podsnosenja>
            <a:prilozi>
                <a:primer_dela>
                    <a:putanja>putanja0</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke0</a:naziv_datoteke>
                </a:primer_dela>
                <a:opis_dela>
                    <a:putanja>putanja1</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke1</a:naziv_datoteke>
                </a:opis_dela>
                <a:punomocje>
                    <a:putanja>putanja2</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke2</a:naziv_datoteke>
                </a:punomocje>
                <a:uplata>
                    <a:putanja>putanja3</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke3</a:naziv_datoteke>
                </a:uplata>
            </a:prilozi>
        </a:Informacije_Zavoda>
        <a:Informacije_Sistema>
            <a:username>username0</a:username>
            <a:email>email0</a:email>
        </a:Informacije_Sistema>
    </a:Zahtev>
    <a:Zahtev>
        <a:Podnosilac xsi:type="a:TFizicko_Lice">
            <a:ime>Petar</a:ime>
            <a:telefon>+38123456789</a:telefon>
            <a:email>pera@gmail.com</a:email>
            <a:prezime>Peric</a:prezime>
            <a:adresa>Maksima Gorkog 10</a:adresa>
            <a:drzavljanstvo>srpsko</a:drzavljanstvo>
        </a:Podnosilac>
        <a:Delo>
            <a:naslov>Izabrana dela</a:naslov>
            <a:alternativni_naslov>Perina izabrana dela</a:alternativni_naslov>
            <a:vrsta_dela>zbirka</a:vrsta_dela>
            <a:forma_zapisa>rukopis</a:forma_zapisa>
            <a:radni_odnos>false</a:radni_odnos>
            <a:nacin_koriscenja>nacin koriscenja</a:nacin_koriscenja>
        </a:Delo>
        <a:Informacije_Zavoda>
            <a:broj_prijave>A-0000-00</a:broj_prijave>
            <a:datum_podsnosenja>2006-05-04</a:datum_podsnosenja>
            <a:prilozi>
                <a:primer_dela>
                    <a:putanja>putanja4</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke4</a:naziv_datoteke>
                </a:primer_dela>
                <a:opis_dela>
                    <a:putanja>putanja5</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke5</a:naziv_datoteke>
                </a:opis_dela>
                <a:punomocje>
                    <a:putanja>putanja6</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke6</a:naziv_datoteke>
                </a:punomocje>
                <a:uplata>
                    <a:putanja>putanja7</a:putanja>
                    <a:naziv_datoteke>naziv_datoteke7</a:naziv_datoteke>
                </a:uplata>
            </a:prilozi>
        </a:Informacije_Zavoda>
        <a:Informacije_Sistema>
            <a:username>username1</a:username>
            <a:email>email1</a:email>
        </a:Informacije_Sistema>
    </a:Zahtev>
</a:Zahtevi>
