=== dusanlazic/xml-ws-2022/zavod/data/z1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
           vc:minVersion="1.0" vc:maxVersion="1.1" targetNamespace="www.zavod.com/Zig"
           xmlns:z="www.zavod.com/Zig">
    <xs:element name="Zahtevi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Zahtev" type="z:TZahtev"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TZahtev">
        <xs:sequence>
            <xs:element name="Podnosilac" type="z:TLice"/>
            <xs:element name="Punomocnik" type="z:TLice"/>
            <xs:element name="Predstavnik" type="z:TLice"/>
            <xs:element name="Zig" type="z:TZig"/>
            <xs:element name="Placanje" type="z:TPlacanje"/>
            <xs:element name="InformacijeZavoda" type="z:TInformacije_Zavoda"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TLice" abstract="true">
        <xs:sequence>
            <xs:element name="adresa" type="z:TAdresa"/>
            <xs:element name="telefon"/>
            <xs:element name="email"/>
            <xs:element name="faks"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_Lice">
        <xs:complexContent>
            <xs:extension base="z:TLice">
                <xs:sequence>
                    <xs:element name="ime"/>
                    <xs:element name="prezime"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPravno_Lice">
        <xs:complexContent>
            <xs:extension base="z:TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TZig">
        <xs:sequence>
            <xs:element name="tip_ziga">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="individualni"/>
                        <xs:element name="kolektivni"/>
                        <xs:element name="garantni"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="tip_znaka">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="verbalni"/>
                        <xs:element name="kombinovani"/>
                        <xs:element name="trodimenzionalni"/>
                        <xs:element name="druga_vrsta"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="boja" type="xs:string"/>
            <xs:element name="transliteracija" type="xs:string"/>
            <xs:element name="prevod" type="xs:string"/>
            <xs:element name="opis" type="xs:string"/>
            <xs:element name="klase_robe">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="klasa">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:maxInclusive value="45"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="pravo_prvenstva" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPlacanje">
        <xs:sequence>
            <xs:element name="osnovna_taksa" type="xs:float"/>
            <xs:element name="taksa_klasa" type="xs:float"/>
            <xs:element name="taksa_grafickog_resenja" type="xs:float"/>
            <xs:element name="ukupna" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TInformacije_Zavoda"/>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="ulica" type="xs:string"/>
            <xs:element name="broj" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="19000"/>
                        <xs:maxInclusive value="25000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dusanlazic/xml-ws-2022/zavod/data/z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<z:Zahtevi xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           xmlns:z="www.zavod.com/Zig"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="www.zavod.com/Zig file:/home/pavle/Documents/XML/Projekat/z1.xsd">
    <z:Zahtev>
        <z:Podnosilac xsi:type="z:TPravno_Lice">
            <z:adresa>
                <z:ulica>ulica0</z:ulica>
                <z:broj>broj0</z:broj>
                <z:mesto>mesto0</z:mesto>
                <z:drzava>drzava0</z:drzava>
                <z:postanski_broj>22000</z:postanski_broj>
            </z:adresa>
            <z:telefon>
            </z:telefon>
            <z:email>
            </z:email>
            <z:faks>
            </z:faks>
            <z:poslovno_ime>
            </z:poslovno_ime>
        </z:Podnosilac>
        <z:Punomocnik xsi:type="z:TPravno_Lice">
            <z:adresa>
                <z:ulica>ulica1</z:ulica>
                <z:broj>broj1</z:broj>
                <z:mesto>mesto1</z:mesto>
                <z:drzava>drzava1</z:drzava>
                <z:postanski_broj>22000</z:postanski_broj>
            </z:adresa>
            <z:telefon>
            </z:telefon>
            <z:email>
            </z:email>
            <z:faks>
            </z:faks>
            <z:poslovno_ime>
            </z:poslovno_ime>
        </z:Punomocnik>
        <z:Predstavnik xsi:type="z:TPravno_Lice">
            <z:adresa>
                <z:ulica>ulica2</z:ulica>
                <z:broj>broj2</z:broj>
                <z:mesto>mesto2</z:mesto>
                <z:drzava>drzava2</z:drzava>
                <z:postanski_broj>22000</z:postanski_broj>
            </z:adresa>
            <z:telefon>
            </z:telefon>
            <z:email>
            </z:email>
            <z:faks>
            </z:faks>
            <z:poslovno_ime>
            </z:poslovno_ime>
        </z:Predstavnik>
        <z:Zig>
            <z:tip_ziga>
                <z:kolektivni>
                </z:kolektivni>
            </z:tip_ziga>
            <z:tip_znaka>
                <z:druga_vrsta>
                </z:druga_vrsta>
            </z:tip_znaka>
            <z:boja>boja0</z:boja>
            <z:transliteracija>transliteracija0</z:transliteracija>
            <z:prevod>prevod0</z:prevod>
            <z:opis>opis0</z:opis>
            <z:klase_robe>
                <z:klasa>23</z:klasa>
            </z:klase_robe>
            <z:pravo_prvenstva>pravo_prvenstva0</z:pravo_prvenstva>
        </z:Zig>
        <z:Placanje>
            <z:osnovna_taksa>0</z:osnovna_taksa>
            <z:taksa_klasa>0</z:taksa_klasa>
            <z:taksa_grafickog_resenja>0</z:taksa_grafickog_resenja>
            <z:ukupna>0</z:ukupna>
        </z:Placanje>
        <z:InformacijeZavoda/>
    </z:Zahtev>
</z:Zahtevi>
